config/routes.rb
Rails.application.routes.draw do
  get "/", to: "welcome#index", as: :root

  get "/studios", to: "studios#index", as: :studios
  get "/studios/new", to: "studios#new", as: :new_studio
  post "/studios", to: "studios#create"
  get "/studios/:id", to: "studios#show", as: :studio
  patch '/studios/:id', to: 'studios#update', as: :update_studio
  delete 'studios/:id', to: 'studios#destroy', as: :delete_studio
  get '/studios/:id/edit', to: 'studios#edit', as: :edit_studio

  get "/studios/:id/yogis", to: "studio_yogis#index", as: :studio_yogis_index
  get "studios/:id/yogis/new", to: "studio_yogis#new", as: :new_studio_yogi
  post "studios/:id/yogis", to: "studio_yogis#create", as: :create_studio_yogi
  
  get "/yogis", to: "yogis#index", as: :yogis
  get "/yogis/:id", to: "yogis#show", as: :yogi
  get "yogis/:id/edit", to: "yogis#edit", as: :edit_yogi
  patch "yogis/:id", to: "yogis#update", as: :update_yogi
  delete "yogis/:id", to: "yogis#destroy", as: :delete_yogi
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :yogis, dependent: :destroy

  def self.order_by
    Studio.order("created_at desc")
  end

  def yogis_count
    self.yogis.count
  end

# As a visitor
# When I visit the Parents Index Page
# Then I see a link to sort parents by the number of `child_table_name` they have
# When I click on the link
# Im taken back to the Parent Index Page where I see all of the parents in order of their count of `child_table_name` (highest to lowest) And, I see the number of children next to each parent name

  # def self.order_by_yogis_count
  #   Studio.joins(:yogis).group(:id).order('count(yogis.id) desc')
  # end

end

app/models/studio_yogi.rb
class StudioYogi < ApplicationRecord
  
end

app/models/yogi.rb
class Yogi < ApplicationRecord
  belongs_to :studio

  scope :members, -> { where(member: true) }

  scope :order_by_name, -> { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/studio_yogis_controller.rb
class StudioYogisController < ApplicationController
  def index
    @studio = Studio.find(params[:id])

    if params[:sort] == "true"
      @yogis = @studio.yogis.order_by_name
    elsif params[:min_age].present?
      @yogis = @studio.yogis.where('age >= ?', params[:min_age])
    else
      @yogis = @studio.yogis
    end
  end

  def new
    @studio = Studio.find(params[:id])
    @yogi = Yogi.new
  end

  def create
    @studio = Studio.find(params[:id])
    @yogi = @studio.yogis.build(yogi_params)
  
    @yogi.save
    
    redirect_to studio_yogis_index_path(@studio)
  end

  private

  def yogi_params
    params.permit(:name, :age, :member)
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  def index
    @studios = Studio.order_by
  end

  def new
  end
  
  def create
    @studio = Studio.new(studio_params)
    
    @studio.save

    redirect_to '/studios'
  end

  def show
    @studio = Studio.find(params[:id])
    @count = @studio.yogis_count
  end

  def edit
    @studio = Studio.find(params[:id])
  end

  def update
    @studio = Studio.find(params[:id])
    @studio.update(studio_params)
    redirect_to studio_path(@studio)
  end

  def destroy
    @studio = Studio.find(params[:id])
    @studio.destroy
    redirect_to '/studios'
  end

  private

  def studio_params
    params.permit(:name, :rating, :accepting_members)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/yogis_controller.rb
class YogisController < ApplicationController
  def index
    if params[:member] == "true"
      @yogis = Yogi.members
    else  
      @yogis = Yogi.all
    end
  end

  def show
    @yogi = Yogi.find(params[:id])
  end

  def edit
    @yogi = Yogi.find(params[:id])
  end

  def update
    @yogi = Yogi.find(params[:id])
    @yogi.update(yogi_params)
    redirect_to yogi_path(@yogi)
  end

  def destroy
    @yogi = Yogi.find(params[:id])
    @yogi.destroy
    redirect_to '/yogis'
  end

  private

  def yogi_params
    params.permit(:name, :age, :member)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YogaStudio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <a><%= link_to 'Home', root_path %></a>
      <div>
        <a><%= link_to 'All Studios', studios_path %></a>
        <a><%= link_to 'All Yogis', yogis_path %></a>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/studio_yogis/index.html.erb
<h1><%= @studio.name %> Yogis</h1>
<h3>Studio ID: <%= @studio.id %></h3>
<a href="/studios/<%= @studio.id %>/yogis?sort=true">Sort by Name</a>

<p><%= form_tag studio_yogis_index_path(@studio), method: :get do %></p>
  <label for="min_age">Minimum Age:</label>
  <input type="number" id="min_age" name="min_age" required>
  
  <button type="submit">Filter by Minimum Age</button>
<p><% end %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Member?</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  <thead>
  <tbody>
    <% @yogis.each do |yogi| %>
      <tr>
        <td><%= yogi.name %></td>
        <td><%= yogi.age %></td>
        <td><%= yogi.member? ? 'Yes' : 'No' %></td>
        <td><%= yogi.created_at %></td>
        <td><%= yogi.updated_at %></td>
        <td><%= link_to 'Edit', edit_yogi_path(yogi) %>
        <td><%= button_to 'Delete', delete_yogi_path(yogi), method: :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= button_to 'New Yogi', new_studio_yogi_path(@studio), method: :get %></p>
<p><%= button_to "All #{@studio.name} Yogis", studio_yogis_index_path(@studio), method: :get %></p>

app/views/studio_yogis/new.html.erb
<h1>Add Yogi to <%= @studio.name %></h1>
<%= form_with(url: studio_yogis_index_path(@studio), method: :post, data: { turbo: false} ) do |form| %>
  <%= form.hidden_field :authenticity_token, value: form_authenticity_token %>

  <label for="name">Name:</label>
  <%= form.text_field :name, id: 'name', required: true %><br><br>

  <label for="age">Age:</label>
  <%= form.number_field :age, id: 'age', min: 1, max: 120, required: true %><br><br>

  <label for="member">Member?</label>
  <%= form.hidden_field :member, value: false %>
  <%= form.check_box :member, id: 'member', value: true %><br><br>

  <button type="submit">Add Yogi</button>
<% end %>

app/views/studios/edit.html.erb
<h1>Edit <%= @studio.name %></h1>
<%= form_with(url: update_studio_path(@studio), method: :patch,  data: { turbo: false }) do |form| %>
  <label for="name">Name:</label>
  <%= form.text_field :name, required: true %><br><br>

  <label for="rating">Rating:</label>
  <%= form.number_field :rating, min: 1, max: 5, required: true %><br><br>

  <label for="accepting_members">Accepting Members?</label>
  <%= form.hidden_field :accepting_members, value: false %>
  <%= form.check_box :accepting_members %><br><br>

  <button type="submit">Update Studio</button>
<% end %>

app/views/studios/index.html.erb
<h1>Studios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Yogis</th>
      <th>Created At</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  <tbody>
    <% @studios.each do |studio| %>
      <tr>
        <td><%= link_to studio.name, studio_path(studio) %></td>
        <td><%= studio.yogis.count %></td>
        <td><%= studio.created_at %></td>
        <td><%= link_to 'Edit', edit_studio_path(studio), method: :get %>
        <td><%= button_to 'Delete', delete_studio_path(studio), method: :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= button_to 'New Studio', new_studio_path, method: :get %></p>

app/views/studios/new.html.erb
<h1>Create New Yoga Studio</h1>
<%= form_with(url: studios_path, method: :post, data: { turbo: false }) do |form| %>
  <%= form.label :name, 'Name:' %>
  <%= form.text_field :name, id: 'name', required: true %><br><br>
  
  <%= form.label :rating, 'Rating:' %>
  <%= form.number_field :rating, id: 'rating', min: 1, max: 5, required: true %><br><br>
  
  <%= form.label :accepting_members, 'Accepting Members?' %>
  <%= form.hidden_field :accepting_members, value: false %>
  <%= form.check_box :accepting_members, id: 'accepting_members' %><br><br>
  
  <%= form.submit 'Create Studio' %>
<% end %>

app/views/studios/show.html.erb
<h3>Studio Details</h3>

<p>Name: <%= @studio.name %></p>
<p>Rating: <%= @studio.rating %></p>
<p>Accepting Members? <%= @studio.accepting_members? ? 'Yes' : 'No' %></p>
<p>Yogis: <%= @studio.yogis_count %></p>
<p>Created Date: <%= @studio.created_at %></p>
<p>Updated Date: <%= @studio.updated_at %></p>


<p><%= button_to 'Update Studio', edit_studio_path(@studio), method: :get %></p>
<p><%= button_to 'View Yogis', studio_yogis_index_path(@studio), method: :get %></p>
<p><%= button_to 'Delete Studio', delete_studio_path(@studio), method: :delete %></p>

app/views/studios/show_yogis.html.erb
<h1><%= @studio.name %> Yogis</h1>
<h3>Studio ID: <%= @studio.id %></h3>
<%= link_to 'Sort by Name', show_studio_yogis_path(@studio, sort: 'name') %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Member?</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th>Update</th>
    </tr>
  <thead>
  <tbody>
    <% @yogis.each do |yogi| %>
      <tr>
        <td><%= yogi.name %></td>
        <td><%= yogi.age %></td>
        <td><%= yogi.member? ? 'Yes' : 'No' %></td>
        <td><%= yogi.created_at %></td>
        <td><%= yogi.updated_at %></td>
        <td><%= link_to 'Edit', edit_yogi_path(yogi) %>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Add Yogi', add_yogi_path(@studio) %></p>

app/views/welcome/index.html.erb
<h1>Welcome to the Yoga Studio Manager<h1>

<ul>
  <li><a href="studios">Studios</a></li>
  <li><a href="studios/new">New Studio</a></li>
  <li><a href="yogis">Yogis</a></li>
</ul>

app/views/yogis/edit.html.erb
<h1>Edit <%= @yogi.name %></h1>
<%= form_with(url: update_yogi_path(@yogi), method: :patch, data: { turbo: false }) do |form| %>
  <label for="name">Name:</label>
  <%= form.text_field :name, required: true %><br><br>

  <label for="age">Age:</label>
  <%= form.number_field :age, min: 16, max: 120, required: true %><br><br>

  <label for="member">Member?</label>
  <%= form.hidden_field :member, value: false %>
  <%= form.check_box :member %><br><br>

  <button type="submit">Update Yogi</button>
<% end %>

app/views/yogis/index.html.erb
<h1>Yogi Members</h1>

<a href="/yogis?member=true">Only Show Members</a>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Member?</th>
      <th>Studio ID</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  <thead>
  <tbody>
    <% @yogis.each do |yogi| %>
      <tr>
        <td><%= link_to yogi.name, yogi_path(yogi) %></td>
        <td><%= yogi.age %></td>
        <td><%= yogi.member? ? 'Yes' : 'No' %></td>
        <td><%= yogi.studio_id %></td>
        <td><%= yogi.created_at %></td>
        <td><%= yogi.updated_at %></td>
        <td><%= link_to 'Edit', edit_yogi_path(yogi) %>
        <td><%= button_to 'Delete', delete_yogi_path(yogi), method: :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/yogis/new.html.erb
<h1>Add New Yogi</h1>
<%= form_with(url: yogis_path, method: :post, data: { turbo: false }) do |form| %>
  <label for="name">Name:</label>
  <input type="text" id="name" name="name" required><br><br>
  
  <label for="age">Age:</label>
  <input type="number" id="age" name="age" min="16" max="120" required><br><br>
  
  <label for="member">Member?</label>
  <input type="checkbox" id="member" name="member"><br><br>
  
  <button type="submit">Add Yogi</button>
<% end %>

app/views/yogis/show.html.erb
<h3>Yogi Details</h3>

<p>Name: <%= @yogi.name %></p>
<p>Age: <%= @yogi.age %></p>
<p>Studio ID: <%= @yogi.studio_id %></p>
<p>Member? <%= @yogi.member? ? 'Yes' : 'No' %></p>
<p>Created Date: <%= @yogi.created_at %></p>
<p>Updated Date: <%= @yogi.updated_at %></p>

<p><%= button_to 'Update Yogi', edit_yogi_path(@yogi), method: :get %></p>
<p><%= button_to 'Delete Yogi', delete_yogi_path(@yogi), method: :delete %></p>